name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build my site
    runs-on: ubuntu-latest
    container:
      image: metacall/guix:latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Are we using Guix?
      run: |
        cat /etc/os-release
          
    # - name: Install Guix
    #   uses: PromyLOPh/guix-install-action@v1.6
    #       
    - name: Install Guile-Commonmark and Haunt
      run: |
        guix pull
        guix install guile guile-commonmark haunt
    #
    # - name: Set up Guix profile
    #   run: echo ". '/var/guix/profiles/per-user/runner/profile/etc/profile'" >> $GITHUB_ENV

    - name: Haunt build
      run: |
        haunt build

    # - uses: actions/cache/save@v3
    #   if: always()
    #   with:
    #     path: ~/.cache/guix
    #     key: guix-cache-${{ github.sha }}

    - name: Deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
