name: Deploy Haunt Site to GitHub Pages

on:
  push:
    branches: [master] # or 'master' if that's your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Guile
      run: |
        sudo apt-get update
        sudo apt-get install -y guile-3.0 guile-3.0-dev git

    - name: Install Haunt
      run: |
        git clone https://git.dthompson.us/haunt.git
        cd haunt
        ./bootstrap
        ./configure
        make
        sudo make install
        cd ..

    - name: Build Haunt site
      run: haunt build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        publish_branch: gh-pages
